#!/bin/bash

echo "Military Alphabet"
echo "-----------------"
echo "A: Alpha"
echo "B: Bravo"
echo "C: Charlie"
echo "D: Delta"
echo "E: Echo"
echo "F: Foxtrot"
echo "G: Golf"
echo "H: Hotel"
echo "I: India"
echo "J: Juliet"
echo "K: Kilo"
echo "L: Lima"
echo "M: Mike"
echo "N: November"
echo "O: Oscar"
echo "P: Papa"
echo "Q: Quebec"
echo "R: Romeo"
echo "S: Sierra"
echo "T: Tango"
echo "U: Uniform"
echo "V: Victor"
echo "W: Whiskey"
echo "X: X-ray"
echo "Y: Yankee"
echo "Z: Zulu"

