# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on # Mouse scroll support on Tmux (disable it on your terminal emulator if needed)
set -g base-index 1 # Setting base window number to 1 
set -g pane-base-index 1
set-option -g renumber-windows on

set-option -g focus-events on # NVIM integration config 
set-option -sg escape-time 0 # zero-out escape time delay

# Sets default terminal for fixing colors inside Neovim 
set -g default-terminal "tmux-256color"
set -ga terminal-features ',xterm-kitty:RGB'
set -g terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -g terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  

set-option -g allow-rename off
set -g monitor-activity on


# ---------------------------------------
# Plugins
# ---------------------------------------
set -g @plugin 'tmux-plugins/tpm' # Plugin manager 
set -g @plugin 'tmux-plugins/tmux-sensible' # Sensible defaults
set -g @plugin 'tmux-plugins/tmux-yank' # System clipboard for tmux yanks
set -g @plugin 'tmux-plugins/tmux-copycat' # System clipboard for tmux yanks
set -g @plugin 'NathanRoark/nathan-tmux-theme'

# Nathan/Dracula theme config
set -g @dracula-plugins "weather spotify-tui"
set -g @dracula-weather-colors "dark_purple white"
set -g @dracula-show-powerline true
set -g @dracula-refresh-rate 5
set -g @dracula-show-empty-plugins true
set -g @dracula-show-left-icon \uebc8

# Initialise TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
