set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-style 'bg=#1F1F25 fg=#666688'
set-window-option -g window-status-current-style bg=#363E4A
set -g window-status-current-style fg=#77CC77
# set -g status-style bg=default,fg=#77DD77
# set -g window-status-style bg=default,fg=#666688
# set -g window-status-current-style bg=default,fg=#C3B1E1


# add spacing between and session name to status bar
set -g status-left-length 64 

# set the left status bar
set-option -g status-left '  #{window_list}'

# set the right status bar with the time and date in human readabl3
set -g status-right '#{session_name}  '

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
